graph TD
style config stroke-width:4px

    subgraph 

    config[config.sh]
    iGrill_config[iGrill_config.ini]
    read_ini[read_ini.sh]
    last_temp[last_temp.sh]
    paths[paths.sh]
    defaults[defaults.sh]
    kasa[kasa.sh]
    stage[stage.sh]
    $food[$food.sh]

    config --- last_temp
    config --- read_ini
    config --- paths
    config --- defaults
    config --- kasa
    config --- stage
    config --- $food

    config -.- iGrill_config
    
end