graph TD
style monitor stroke-width:4px
style data stroke-width:4px

    subgraph 
    monitor[monitor.py]
    igrill[igrill.py]
    logging[logging.py]
    mac_config[mac_config.py]
    limits[limits.ini]
    iGrill_config[iGrill_config.ini]
    data[data.sh]

    monitor --- igrill
    monitor --- logging
    monitor --- mac_config
    monitor -.- iGrill_config
    igrill -.- limits
    monitor ==> data
end