graph TD
style config stroke-width:4px
style monitor stroke-width:4px
style start_smoking stroke-width:4px
    subgraph 

    start_smoking[start_smoking.sh]
    buzzer_daemon[buzzer_daemon.py]
    buzzer_client[buzzer_client.py]
    kasa_daemon[kasa_daemon.py]
    kasa_client[kasa_client.py]
    ssrc_daemon[ssrc_daemon.py]
    ssrc_client[ssrc_client.py]
config[config.sh]
    items[items.json]
paths[paths.sh]      
limits[limits.sh]          
limits_ini[limits.ini]
                gen_json[gen_json.sh]
                get_mac[get_mac.sh]
                mac_config[mac_config.py]
            monitor[bt_monitor.py]
                bt[bt.sh]
start_smoking --- config
gen_json --- paths
start_smoking --- gen_json
start_smoking --- limits
start_smoking --- paths
start_smoking --- bt
start_smoking --- get_mac
start_smoking ==> buzzer_daemon
start_smoking ==> ssrc_client
ssrc_client --> ssrc_daemon
start_smoking ==> buzzer_client
buzzer_client --> buzzer_daemon
start_smoking ==> ssrc_daemon
ssrc_daemon --> kasa_daemon
kasa_client --> kasa_daemon
get_mac -.- mac_config
gen_json -.- items
gen_json --- config
limits --- paths
limits -.- limits_ini
start_smoking ==> monitor
start_smoking ==> kasa_daemon
end